//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NECPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_M
    {
        public string SupId { get; set; }
        public string SupName { get; set; }
        public string SupShortName { get; set; }
        public string ContactPerson { get; set; }
        public string ShipType { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string VendorCreatDate { get; set; }
        public string IST_Date { get; set; }
        public string IEN_Date { get; set; }
        public string StopTranDate_S { get; set; }
        public string StopTranDate_E { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DataDate { get; set; }
        public string UserID { get; set; }
    }
}
