//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDO.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MvcSitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcSitemap() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDO.App_GlobalResources.MvcSitemap", typeof(MvcSitemap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 關於 的當地語系化字串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公告模組 的當地語系化字串。
        /// </summary>
        public static string Announce {
            get {
                return ResourceManager.GetString("Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公告設定 的當地語系化字串。
        /// </summary>
        public static string Announce_1 {
            get {
                return ResourceManager.GetString("Announce_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單模組 的當地語系化字串。
        /// </summary>
        public static string eFormModule {
            get {
                return ResourceManager.GetString("eFormModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單設定 的當地語系化字串。
        /// </summary>
        public static string eFormModule_1 {
            get {
                return ResourceManager.GetString("eFormModule_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單填寫 的當地語系化字串。
        /// </summary>
        public static string eFormModule_2 {
            get {
                return ResourceManager.GetString("eFormModule_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表單簽核 的當地語系化字串。
        /// </summary>
        public static string eFormModule_3 {
            get {
                return ResourceManager.GetString("eFormModule_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程模組 的當地語系化字串。
        /// </summary>
        public static string FlowModule {
            get {
                return ResourceManager.GetString("FlowModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程日誌 的當地語系化字串。
        /// </summary>
        public static string FlowModule_1 {
            get {
                return ResourceManager.GetString("FlowModule_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程角色 的當地語系化字串。
        /// </summary>
        public static string FlowModule_2 {
            get {
                return ResourceManager.GetString("FlowModule_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程設定 的當地語系化字串。
        /// </summary>
        public static string FlowModule_3 {
            get {
                return ResourceManager.GetString("FlowModule_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 框架展示 的當地語系化字串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件模組 的當地語系化字串。
        /// </summary>
        public static string MailModule {
            get {
                return ResourceManager.GetString("MailModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件日誌 的當地語系化字串。
        /// </summary>
        public static string MailModule_1 {
            get {
                return ResourceManager.GetString("MailModule_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件角色 的當地語系化字串。
        /// </summary>
        public static string MailModule_2 {
            get {
                return ResourceManager.GetString("MailModule_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件範本 的當地語系化字串。
        /// </summary>
        public static string MailModule_3 {
            get {
                return ResourceManager.GetString("MailModule_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 實作範例 的當地語系化字串。
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CSS 的當地語系化字串。
        /// </summary>
        public static string Sample_1 {
            get {
                return ResourceManager.GetString("Sample_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Javascript 的當地語系化字串。
        /// </summary>
        public static string Sample_2 {
            get {
                return ResourceManager.GetString("Sample_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自訂控制項 的當地語系化字串。
        /// </summary>
        public static string Sample_3 {
            get {
                return ResourceManager.GetString("Sample_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 表格 的當地語系化字串。
        /// </summary>
        public static string Sample_4 {
            get {
                return ResourceManager.GetString("Sample_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料控制層 的當地語系化字串。
        /// </summary>
        public static string Sample_5 {
            get {
                return ResourceManager.GetString("Sample_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 App Code 的當地語系化字串。
        /// </summary>
        public static string Sample_6 {
            get {
                return ResourceManager.GetString("Sample_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程API 的當地語系化字串。
        /// </summary>
        public static string Sample_7 {
            get {
                return ResourceManager.GetString("Sample_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SDO API 的當地語系化字串。
        /// </summary>
        public static string Sample_8 {
            get {
                return ResourceManager.GetString("Sample_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 動態表單 的當地語系化字串。
        /// </summary>
        public static string Sample_9 {
            get {
                return ResourceManager.GetString("Sample_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 架構規範 的當地語系化字串。
        /// </summary>
        public static string Spec {
            get {
                return ResourceManager.GetString("Spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Web.config 的當地語系化字串。
        /// </summary>
        public static string Spec_1 {
            get {
                return ResourceManager.GetString("Spec_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SESSION 的當地語系化字串。
        /// </summary>
        public static string Spec_2 {
            get {
                return ResourceManager.GetString("Spec_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日誌 的當地語系化字串。
        /// </summary>
        public static string Spec_3 {
            get {
                return ResourceManager.GetString("Spec_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 共用版面 的當地語系化字串。
        /// </summary>
        public static string Spec_4 {
            get {
                return ResourceManager.GetString("Spec_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息庫 的當地語系化字串。
        /// </summary>
        public static string Spec_5 {
            get {
                return ResourceManager.GetString("Spec_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 麵包屑 的當地語系化字串。
        /// </summary>
        public static string Spec_6 {
            get {
                return ResourceManager.GetString("Spec_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統管理模組 的當地語系化字串。
        /// </summary>
        public static string Sysop {
            get {
                return ResourceManager.GetString("Sysop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string Sysop_1 {
            get {
                return ResourceManager.GetString("Sysop_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色 的當地語系化字串。
        /// </summary>
        public static string Sysop_2 {
            get {
                return ResourceManager.GetString("Sysop_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權利 的當地語系化字串。
        /// </summary>
        public static string Sysop_3 {
            get {
                return ResourceManager.GetString("Sysop_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能 的當地語系化字串。
        /// </summary>
        public static string Sysop_4 {
            get {
                return ResourceManager.GetString("Sysop_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代理人 的當地語系化字串。
        /// </summary>
        public static string Sysop_5 {
            get {
                return ResourceManager.GetString("Sysop_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織 的當地語系化字串。
        /// </summary>
        public static string Sysop_6 {
            get {
                return ResourceManager.GetString("Sysop_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統參數 的當地語系化字串。
        /// </summary>
        public static string Sysop_7 {
            get {
                return ResourceManager.GetString("Sysop_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料庫日誌 的當地語系化字串。
        /// </summary>
        public static string Sysop_8 {
            get {
                return ResourceManager.GetString("Sysop_8", resourceCulture);
            }
        }
    }
}
